[package]
name = "systemrdl-fmt"
version.workspace = true
edition.workspace = true

[dependencies]
rowan = { workspace = true }
systemrdl-syntax = { path = "../systemrdl-syntax" }

# Binary only. The library half of this crate depends on none of these.
anstyle = { workspace = true }
clap = { workspace = true }
similar = { workspace = true }
